# Generated by Django 4.0.3 on 2022-03-20 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_food_macros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='grams',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='macros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.macros'),
        ),
        migrations.AlterField(
            model_name='macros',
            name='carbs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='macros',
            name='fat',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='macros',
            name='protein',
            field=models.PositiveIntegerField(),
        ),
    ]
