# Generated by Django 4.0.3 on 2022-03-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_alter_food_calories_alter_food_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='macros',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cal.macros'),
        ),
    ]
