# Generated by Django 4.0.3 on 2022-03-27 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_food_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cal_day', models.PositiveIntegerField()),
                ('associated_date', models.DateField(default=datetime.date.today)),
                ('total_foods_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.food')),
            ],
        ),
    ]
