# Generated by Django 4.0.3 on 2022-04-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_alter_food_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='total_foods_day',
        ),
        migrations.AddField(
            model_name='counter',
            name='total_foods_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cal.food'),
            preserve_default=False,
        ),
    ]
