# Generated by Django 4.0.3 on 2022-04-02 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0011_remove_counter_total_foods_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='usr',
        ),
        migrations.AddField(
            model_name='counter',
            name='usr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
